checks:
  php: true

tools:
  external_code_coverage: true
  php_code_sniffer:
    config:
      standard: "PSR2"
  php_cs_fixer:
      config: { level: psr2 }

filter:
  excluded_paths:
    - tests/*

