language: php
php:
    - 5.5
    - 5.6
    - hhvm
before_script: composer install
script: phpunit
after_script:
    - phpunit --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
